### ISSUE TITLE
Test videos - 28 video pairs (3.63 GB) is empty

### ISSUE THREAD

**Issue by FlyingAnt2018** [harinduravin/DualCam#1]
Hello, test videos folder is empty.

**Comment by harinduravin** [comment]
We will try to restore. We have mistakenly allowed edit access for the files.

**Comment by harinduravin** [comment]
Video files are now restored.

![image](https://github.com/harinduravin/DualCam/assets/56308645/4a27d8ae-018d-4ea3-acd3-1813b2bbee10)
